Repository channable/hoff, pull requests merged in 2022-06, with the labels that each got.

#115 Abort merge after an "empty" rebase
  src/Git.hs
  src/Logic.hs
  src/Project.hs
  tests/EventLoopSpec.hs
  tests/Spec.hs
Labels: bug

#120 Detect failing nix builds on CI
  .semaphore/semaphore.yml
Labels: bug, testing, hackathon

#121 Hackathon: make Hoff interface a little more "hoffelijk" (courteous)
  src/WebInterface.hs
  static/style.css
Labels: enhancement, hackathon
