Repository channable/hoff, pull requests merged in 2022-07, with the labels that each got.

#126 Improve developer instructions and replace the send-webhook script
  .gitignore
  doc/example-dev-config.json
  readme.md
  tools/build-status
  tools/comment
  tools/send-webhook
  tools/send-webhook.py
Labels: enhancement, documentation, devex

#136 use `mount_nix_store` to avoid running out of disk on Semaphore CI
  .semaphore/prologue.sh
  .semaphore/semaphore.yml
Labels: bug

#131 Merge train: infer candidate from state
  src/Logic.hs
  src/Project.hs
  tests/EventLoopSpec.hs
  tests/Spec.hs
Labels: refactor

#139 Test comments looping back from GitHub
  tests/Spec.hs
Labels: testing

#138 Report URLs of pending status checks
  src/EventLoop.hs
  src/Logic.hs
  src/Project.hs
  src/WebInterface.hs
  tests/EventLoopSpec.hs
  tests/Spec.hs
  tools/send-webhook
Labels: enhancement

#143 Test the build status comment.
  tests/Spec.hs
Labels: testing

#141 (Re-)infer candidate from state
  src/Logic.hs
  src/Project.hs
  tests/EventLoopSpec.hs
  tests/Spec.hs
Labels: bug, enhancement

#145 Ignore duplicate build status webhooks
  src/Logic.hs
  tests/Spec.hs
Labels: bug
